### PR TITLE
Platforms

### PR DESCRIPTION
**Pull request by tjakob**
closes #43 
Add builds for these new platforms.
Requires an explicit dependency on make.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
linux seems to fail :(

**Comment by mariusvniekerk** [comment]
we could merge it to get the other platforms going?

**Comment by pkgw** [comment]
The Linux fail seems to be a problem with the latest `gobject-introspection` package on Linux; the `g-ir-compiler` binary doesn't seem to have any rpath info. No evidence that it's anything to do with harfbuzz.

**Comment by pkgw** [comment]
Cf conda-forge/gobject-introspection-feedstock#13

**Comment by tjakob** [comment]
@pkgw Thank you for the gobject-introspection fix. It looks like everything is working here now.

**Comment by tjakob** [comment]
@mariusvniekerk Can you merge this one?
It is needed by some other packages.

**Comment by scopatz** [comment]
I think that @pkgw @ocefpaf would be OK with me merging this, but @tjakob would you be willing to add yourself as a maintainer?

**Comment by pkgw** [comment]
FWIW, definitely happy to see this merged! I'm on my mobile and apparently there's some issue with two-factor authentication so that I can't actually log in to do so, though.

Peter

**Comment by scopatz** [comment]
Alright, merging for @pkgw :wink:

**Pull request merged**
