### PR TITLE
Bump to 2.7.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Hmmm looks like I lost my azure builds! Any ideas on how to get them back?

**Comment by pkgw** [comment]
@conda-forge-admin, please restart ci

**Comment by pkgw** [comment]
^^^ we'll see if the above helps

Oh, but it probably won't. Based on some other things I've seen, I think that Azure Pipeline builds won't run on draft PRs (by default?). Try turning this into a non-draft.

**Comment by tschoonj** [comment]
Thanks @pkgw , I didn't know that Azure Pipelines didn't kick in for draft PRs...

**Comment by tschoonj** [comment]
This PR also adds CoreText support on macOS. See #45

**Comment by tschoonj** [comment]
I disabled gobject-introspection on Windows until https://github.com/harfbuzz/harfbuzz/issues/2643 is fixed.

**Comment by tschoonj** [comment]
Yep, think it's all good. Next on my list is updating pango...

**Pull request merged**
